/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.FachadaAplicacion;

/**
 *
 * @author alumnogreibd
 */
public class VEstadisticas extends javax.swing.JDialog {

    /**
     * Creates new form VEstadisticas
     */
    private FachadaAplicacion fa;
    
    public VEstadisticas(java.awt.Frame parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        initComponents();
        numIncidencias.setText(fa.numeroIncidencias().toString());
        incidenciasMortales.setText(fa.numeroIncidenciasMortales().toString());
        diasIncidencias.setText(fa.diasUltimaIncidencia().toString());
        numTotalDinos.setText(fa.numeroTotalDinos().toString());
        numVivos.setText(fa.numeroDinosVivos().toString());
        porcVivos.setText(String.valueOf(fa.porcentajeDinosVivos()));
        numMuertos.setText(fa.numeroDinosMuertos().toString());
        porcMuertos.setText(String.valueOf(fa.porcentajeDinosMuertos()));
        diasParque.setText(fa.mediaDiasDinos().toString());
        numEspecies.setText(fa.numeroEspecies().toString());
        gastoMedioEmpleado.setText(String.valueOf(fa.gastoMedioEmpleado()));
        empleadosMejorSueldo.setText(fa.empleadosMejorSueldo().toString());
        guiaMasActividades.setText(fa.guiaMasActividades());
        anhoMasIncidencias.setText(fa.anhoMasIncidencias().toString());
        actividadCara.setText(fa.actividadCara());
        
        ModeloListaStrings d = new ModeloListaStrings();
        listaDietas.setModel(d);
        d.setElementos(fa.dietaComun());
        ModeloListaStrings c = new ModeloListaStrings();
        listaDinoConflictivo.setModel(c);
        c.setElementos(fa.dinoConflictivo());
        ModeloListaStrings n = new ModeloListaStrings();
        listaDinoNoConflictivo.setModel(n);
        n.setElementos(fa.dinoNoConflictivo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        Actividades = new javax.swing.JTabbedPane();
        panelActividades = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        guiaMasActividades = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        actividadCara = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        panelEmpleados = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        gastoMedioEmpleado = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        empleadosMejorSueldo = new javax.swing.JTextField();
        panelDinosaurios = new javax.swing.JPanel();
        diasParque = new javax.swing.JTextField();
        numEspecies = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDietas = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaDinoConflictivo = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        numTotalDinos = new javax.swing.JTextField();
        numMuertos = new javax.swing.JTextField();
        numVivos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        porcMuertos = new javax.swing.JTextField();
        porcVivos = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaDinoNoConflictivo = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        panelIncidencias = new javax.swing.JPanel();
        numIncidencias = new javax.swing.JTextField();
        incidenciasMortales = new javax.swing.JTextField();
        diasIncidencias = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        anhoMasIncidencias = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estadísticas del parque");

        jLabel1.setText("Guía con más actividades:");

        guiaMasActividades.setEditable(false);

        jLabel20.setText("Actividad más cara:");

        actividadCara.setEditable(false);
        actividadCara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actividadCaraActionPerformed(evt);
            }
        });

        jLabel21.setText("€");

        javax.swing.GroupLayout panelActividadesLayout = new javax.swing.GroupLayout(panelActividades);
        panelActividades.setLayout(panelActividadesLayout);
        panelActividadesLayout.setHorizontalGroup(
            panelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActividadesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel20))
                .addGap(31, 31, 31)
                .addGroup(panelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guiaMasActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelActividadesLayout.createSequentialGroup()
                        .addComponent(actividadCara, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        panelActividadesLayout.setVerticalGroup(
            panelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActividadesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(guiaMasActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(actividadCara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(552, Short.MAX_VALUE))
        );

        Actividades.addTab("Actividades", panelActividades);

        jLabel16.setText("Gasto medio por empleado:");

        gastoMedioEmpleado.setEditable(false);

        jLabel18.setText("€");

        jLabel14.setText("Empleados más sueldo de la media:");

        empleadosMejorSueldo.setEditable(false);

        javax.swing.GroupLayout panelEmpleadosLayout = new javax.swing.GroupLayout(panelEmpleados);
        panelEmpleados.setLayout(panelEmpleadosLayout);
        panelEmpleadosLayout.setHorizontalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(empleadosMejorSueldo, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(gastoMedioEmpleado))
                .addGap(9, 9, 9)
                .addComponent(jLabel18)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        panelEmpleadosLayout.setVerticalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(gastoMedioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(30, 30, 30)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(empleadosMejorSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(542, Short.MAX_VALUE))
        );

        Actividades.addTab("Empleados", panelEmpleados);

        diasParque.setEditable(false);

        numEspecies.setEditable(false);

        jLabel13.setText("Dieta/s más común:");

        jScrollPane1.setViewportView(listaDietas);

        jScrollPane2.setViewportView(listaDinoConflictivo);

        jLabel7.setText("%");

        jLabel8.setText("%");

        jLabel9.setText("Núm. total dinosaurios:");

        jLabel10.setText("Núm. especies:");

        jLabel11.setText("Vida media en el parque:");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setText("días");

        numTotalDinos.setEditable(false);

        numMuertos.setEditable(false);

        numVivos.setEditable(false);

        jLabel3.setText("Dinosaurio/s más conflictivo:");

        jLabel5.setText("Vivos:");

        jLabel6.setText("Muertos:");

        porcMuertos.setEditable(false);

        porcVivos.setEditable(false);

        jScrollPane3.setViewportView(listaDinoNoConflictivo);

        jLabel4.setText("Dinosaurios/s no conflictivos:");

        javax.swing.GroupLayout panelDinosauriosLayout = new javax.swing.GroupLayout(panelDinosaurios);
        panelDinosaurios.setLayout(panelDinosauriosLayout);
        panelDinosauriosLayout.setHorizontalGroup(
            panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDinosauriosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDinosauriosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDinosauriosLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numTotalDinos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelDinosauriosLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelDinosauriosLayout.createSequentialGroup()
                        .addGroup(panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDinosauriosLayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDinosauriosLayout.createSequentialGroup()
                                .addGroup(panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDinosauriosLayout.createSequentialGroup()
                                .addComponent(numVivos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(porcVivos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))
                            .addGroup(panelDinosauriosLayout.createSequentialGroup()
                                .addComponent(numMuertos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(porcMuertos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDinosauriosLayout.createSequentialGroup()
                                .addComponent(diasParque, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12))
                            .addComponent(numEspecies, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(87, Short.MAX_VALUE))))
        );
        panelDinosauriosLayout.setVerticalGroup(
            panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDinosauriosLayout.createSequentialGroup()
                .addGroup(panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDinosauriosLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDinosauriosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numTotalDinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numVivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcVivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numMuertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcMuertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diasParque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGroup(panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDinosauriosLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel13))
                    .addGroup(panelDinosauriosLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numEspecies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(27, 27, 27)
                .addGroup(panelDinosauriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDinosauriosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        Actividades.addTab("Dinosaurios", panelDinosaurios);

        numIncidencias.setEditable(false);

        incidenciasMortales.setEditable(false);

        diasIncidencias.setEditable(false);
        diasIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasIncidenciasActionPerformed(evt);
            }
        });

        jLabel15.setText("Núm. incidencias:");

        jLabel17.setText("Núm. incidencias mortales:");

        jLabel19.setText("Días sin incidencias:");

        jLabel2.setText("Año con más incidencias:");

        anhoMasIncidencias.setEditable(false);

        javax.swing.GroupLayout panelIncidenciasLayout = new javax.swing.GroupLayout(panelIncidencias);
        panelIncidencias.setLayout(panelIncidenciasLayout);
        panelIncidenciasLayout.setHorizontalGroup(
            panelIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIncidenciasLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(panelIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(diasIncidencias, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(numIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incidenciasMortales)
                    .addComponent(anhoMasIncidencias))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        panelIncidenciasLayout.setVerticalGroup(
            panelIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIncidenciasLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(36, 36, 36)
                .addGroup(panelIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(incidenciasMortales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panelIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diasIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(32, 32, 32)
                .addGroup(panelIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(anhoMasIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(441, Short.MAX_VALUE))
        );

        Actividades.addTab("Incidencias", panelIncidencias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Actividades)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Actividades, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diasIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasIncidenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diasIncidenciasActionPerformed

    private void actividadCaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actividadCaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actividadCaraActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Actividades;
    private javax.swing.JTextField actividadCara;
    private javax.swing.JTextField anhoMasIncidencias;
    private javax.swing.JTextField diasIncidencias;
    private javax.swing.JTextField diasParque;
    private javax.swing.JTextField empleadosMejorSueldo;
    private javax.swing.JTextField gastoMedioEmpleado;
    private javax.swing.JTextField guiaMasActividades;
    private javax.swing.JTextField incidenciasMortales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listaDietas;
    private javax.swing.JList listaDinoConflictivo;
    private javax.swing.JList listaDinoNoConflictivo;
    private javax.swing.JTextField numEspecies;
    private javax.swing.JTextField numIncidencias;
    private javax.swing.JTextField numMuertos;
    private javax.swing.JTextField numTotalDinos;
    private javax.swing.JTextField numVivos;
    private javax.swing.JPanel panelActividades;
    private javax.swing.JPanel panelDinosaurios;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel panelIncidencias;
    private javax.swing.JTextField porcMuertos;
    private javax.swing.JTextField porcVivos;
    // End of variables declaration//GEN-END:variables
}
